const SUCESS_CODE = 0  // 成功
const NEED_FILL_INFORMATION_CODE = 1003  // 需要完善信息
const GUAN_SUCCESS_WITH_NOTI_MIN_CODE = 9000  // 成功但是需要提醒
const RESP_SIGN_INVALID = 1004  // 签名验证失败

module.exports = {
  SUCESS_CODE,
  NEED_FILL_INFORMATION_CODE,
  GUAN_SUCCESS_WITH_NOTI_MIN_CODE,
  RESP_SIGN_INVALID
}
