const SUCESS_CODE = 0  // 成功
const NEED_FILL_INFORMATION_CODE = 1003  // 需要完善信息
const GUAN_SUCCESS_WITH_NOTI_MIN_CODE = 9000  // 成功但是需要提醒

const MODEL_USER_OP_TYPE_BIRTH_YEAR = 2
const MODEL_USER_OP_TYPE_HEIGHT = 4
const MODEL_USER_OP_TYPE_WEIGHT = 5
const MODEL_USER_OP_TYPE_MONTH_PAY = 6
const MODEL_USER_OP_TYPE_BIRTH_YEAR_PERIOD = 8
const MODEL_USER_OP_TYPE_HEIGHT_PERIOD = 9
const MODEL_USER_OP_TYPE_WEIGHT_PERIOD = 10
const MODEL_USER_OP_TYPE_MONTH_PAY_PERIOD = 11
module.exports = {
  SUCESS_CODE,
  NEED_FILL_INFORMATION_CODE,
  MODEL_USER_OP_TYPE_BIRTH_YEAR,
  MODEL_USER_OP_TYPE_HEIGHT,
  MODEL_USER_OP_TYPE_WEIGHT,
  MODEL_USER_OP_TYPE_MONTH_PAY,
  MODEL_USER_OP_TYPE_BIRTH_YEAR_PERIOD,
  MODEL_USER_OP_TYPE_HEIGHT_PERIOD,
  MODEL_USER_OP_TYPE_WEIGHT_PERIOD,
  MODEL_USER_OP_TYPE_MONTH_PAY_PERIOD,
  GUAN_SUCCESS_WITH_NOTI_MIN_CODE
}
